--テーブルの作成
CREATE TABLE CLASS_NUM
(SCHOOL_CD CHAR(3) NOT NULL , CLASS_NUM VARCHAR(5) NOT NULL , PRIMARY KEY(SCHOOL_CD , CLASS_NUM));

--サンプルデータの挿入
INSERT INTO CLASS_NUM VALUES('oom' , '131');
INSERT INTO CLASS_NUM VALUES('oom' , '132');