--テーブルの作成
CREATE TABLE SUBJECT
(SCHOOL_CD CHAR(3) NOT NULL,
CD CHAR(3) NOT NULL,
NAME VARCHAR(20) DEFAULT NULL,
PRIMARY KEY(SCHOOL_CD , CD));

--サンプルデータの挿入
INSERT INTO SUBJECT VALUES
('OOM' , 'A02' , '国語');