--テーブルの作成
CREATE TABLE TEACHER
(ID VARCHAR(10) PRIMARY KEY NOT NULL,
PASSWORD VARCHAR(30) DEFAULT NULL,
NAME VARCHAR(10) DEFAULT NULL,
SCHOOL_CD CHAR(3) DEFAULT NULL);

--サンプルデータの挿入
INSERT INTO TEACHER VALUES
('admin' , 'password' , '大原花子' , 'oom');