--テーブルの作成
CREATE TABLE TEST
(STUDENT_NO VARCHAR(10) NOT NULL,
SUBJECT_CD CHAR(3) NOT NULL,
SCHOOL_CD CHAR(10) NOT NULL,
NO INTEGER(10) NOT NULL,
POINT INTEGER(10) DEFAULT NULL,
CLASS_NUM VARCHAR(5) DEFAULT NULL,
PRIMARY KEY(STUDENT_NO , SUBJECT_CD , SCHOOL_CD , NO));

--サンプルデータの挿入
INSERT INTO TEST VALUES
('2231111' , 'A02' , 'oom' , 1 , 100 , '131');